
server:
  port: 8077
spring:
  application:
    name: customer-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: root
  jpa:
    hibernate:
      #used to update the existinf table , rather than creating a new one
      ddl-auto: update
    database: postgresql
    #Used for generate postgres specific synatx , as different sql's have different syntax
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    prefer-ip-address: true  # Register with IP address instead of hostname
